controller:
  image:
    image: ingress-nginx/controller
    tag: "v1.13.4"

  service:
    type: ClusterIP
    externalIPs:
      - 192.168.56.30

  ingressClassResource:
    name: nginx
    default: true

  extraEnvs:
    - name: TZ
      value: Asia/Seoul

  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: k8s-master

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"