config:
  argocd:
    serverAddress: "https://argo-cd-argocd-server"

  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      #credentials: env:DOCKER_HUB_CREDS=username:passowrd

