nginxGateway:

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

  nodeSelector:
    kubernetes.io/hostname: k8s-master
  metrics:
    enable: false

certGenerator:
  enable: false
